### ISSUE TITLE
BUILD FAILED (Raspbian 9.9 using ruby-build 20190423)

### ISSUE THREAD

**Issue by ultrasam** [rbenv/rbenv#1160]
I am getting that error after successfully installing rbenv in my Raspberry Pi 3, but when trying to do:
rbenv install 2.6.3

This is the output I get:
```
Downloading ruby-2.6.3.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.3.tar.bz2
Installing ruby-2.6.3...
ruby-build: use readline from homebrew

BUILD FAILED (Raspbian 9.9 using ruby-build 20190423)

Inspect or clean up the working tree at /tmp/ruby-build.20190513084815.18923
Results logged to /tmp/ruby-build.20190513084815.18923.log

Last 10 log lines:
	from /tmp/ruby-build.20190513084815.18923/ruby-2.6.3/lib/rubygems/package.rb:44:in `<top (required)>'
	from /tmp/ruby-build.20190513084815.18923/ruby-2.6.3/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /tmp/ruby-build.20190513084815.18923/ruby-2.6.3/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /tmp/ruby-build.20190513084815.18923/ruby-2.6.3/lib/rubygems/installer.rb:11:in `<top (required)>'
	from /tmp/ruby-build.20190513084815.18923/ruby-2.6.3/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /tmp/ruby-build.20190513084815.18923/ruby-2.6.3/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./tool/rbinstall.rb:703:in `<module:RbInstall>'
	from ./tool/rbinstall.rb:639:in `<main>'
uncommon.mk:364: recipe for target 'do-install-all' failed
make: *** [do-install-all] Error 1
```
I am attaching here the log file.
[ruby-build.20190513084815.18923.log](https://github.com/rbenv/rbenv/files/3173996/ruby-build.20190513084815.18923.log)

Any help would be appreciated.

Thanks,

**Comment by ultrasam** [comment]
After a lot of searching on the internet, I found a solution but I would like an explanation if possible.

I ran the following command:

`brew unlink openssl`

then I executed:
`rbenv install 2.6.3`

and everything worked

**Comment by nzerobe** [comment]
```vagrant@ubuntu-xenial:~$ brew unlink openssl

Command 'brew' not found, but can be installed with:

apt install linuxbrew-wrapper
Please ask your administrator.

vagrant@ubuntu-xenial:~$ apt install linuxbrew-wrapper
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?```
