### ISSUE TITLE
Failed to build gem native extension.

### ISSUE THREAD

**Issue by jubishop** [rbenv/rbenv#1309]
I have tried all the things I can find to fix this on OSX (Big Sur).

I have run `xcode-select install` just fine, everything is in `/Library/Developer/CommandLineTools`, the env var $SDKROOT is set to `Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`, which is the output from `xcrun --sdk macosx --show-sdk-path`.

I'm using ruby 3.0.0 from rbenv, my `which ruby` shows `/Users/jubishop/.rbenv/shims/ruby`, and `which gem` shows `/Users/jubishop/.rbenv/shims/gem`.  I've tried setting the CPPFLAGS and all those other env vars people suggest, but no matter what I do, `sudo gem update` still fails to build any gem native extension.  

Standard `gcc` on the command line works for me.  I can create a `hello_world.c` file, build it, and see it print `Hello World!`.  

Please god help me.  🙏

**Comment by jubishop** [comment]
this is the error I get:

```
/Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/3.0.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/3.0.0/mkmf.rb:564:in `try_link0'
	from /Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/3.0.0/mkmf.rb:582:in `try_link'
	from /Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/3.0.0/mkmf.rb:794:in `try_func'
	from /Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/3.0.0/mkmf.rb:1083:in `block in have_func'
	from /Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/3.0.0/mkmf.rb:971:in `block in checking_for'
	from /Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/3.0.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/3.0.0/mkmf.rb:331:in `open'
	from /Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/3.0.0/mkmf.rb:361:in `block in postpone'
	from /Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/3.0.0/mkmf.rb:331:in `open'
	from /Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/3.0.0/mkmf.rb:357:in `postpone'
	from /Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/3.0.0/mkmf.rb:970:in `checking_for'
	from /Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/3.0.0/mkmf.rb:1082:in `have_func'
	from extconf.rb:6:in `<main>'
```

**Comment by jubishop** [comment]
If I look in the suggested `mkmf.log` files I see:

```
"clang -fdeclspec -o conftest -I/Users/jubishop/.rbenv/versions/3.0.0/include/ruby-3.0.0/x86_64-darwin20 -I/Users/jubishop/.rbenv/versions/3.0.0/include/ruby-3.0.0/ruby/backward -I/Users/jubishop/.rbenv/versions/3.0.0/include/ruby-3.0.0 -I. -I/Users/jubishop/.rbenv/versions/3.0.0/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens  -fno-common -pipe conftest.c  -L. -L/Users/jubishop/.rbenv/versions/3.0.0/lib -L. -L/Users/jubishop/.rbenv/versions/3.0.0/lib  -fstack-protector-strong     -lruby.3.0   "
In file included from conftest.c:1:
In file included from /Users/jubishop/.rbenv/versions/3.0.0/include/ruby-3.0.0/ruby.h:38:
In file included from /Users/jubishop/.rbenv/versions/3.0.0/include/ruby-3.0.0/ruby/ruby.h:23:
/Users/jubishop/.rbenv/versions/3.0.0/include/ruby-3.0.0/ruby/defines.h:16:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

```

**Comment by jubishop** [comment]
I can see the `-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk` in the `clang` command yet still it fails! :(

**Comment by jubishop** [comment]
ok this actually worked,  I'm not sure why/which was needed tho `sudo gem update -- --with-opt-include=$SDKROOT/usr --with-opt-lib=$SDKROOT/usr --with-opt-dir=$SDKROOT/usr`

**Comment by jubishop** [comment]
turns out `sudo gem update -- --with-opt-dir=$SDKROOT/usr` is the ticket.

**Comment by jubishop** [comment]
I'd love to know why, and what is the cleaner way to solve this?

**Comment by partounian** [comment]
This seemed to fix my gem building issues `sudo chown -R patrick: /Users/patrick/.rbenv/ && rbenv rehash`

**Comment by mislav** [comment]
@jubishop Thanks for sharing your workaround. This project only manages switching Ruby versions, and if something fails when running `ruby` or `gem install`, that is not the problem with the version manager anymore. We cannot offer support for this type of issue.
