### ISSUE TITLE
bundler: failed to load command: thin (/home/ots/.rbenv/versions/2.6.10/bin/thin)

### ISSUE THREAD

**Issue by ralvaradora** [rbenv/rbenv#1420]
I have this issue when i run this command 
```
ots@Onetime:~/onetimesecret$ bundle exec thin -e dev -R config.ru -p 7143 start


bundler: failed to load command: thin (/home/ots/.rbenv/versions/2.6.10/bin/thin)
/home/ots/onetimesecret/lib/onetime.rb:52:in `load!': undefined method `gibbler' for ["Onetime", "ots", 21835, "0.10.1", 1660858516]:Array (NoMethodError)
        from config.ru:30:in `block in <main>'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/rack-2.1.4.1/lib/rack/builder.rb:71:in `instance_eval'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/rack-2.1.4.1/lib/rack/builder.rb:71:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `eval'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `load'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/thin-1.8.1/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/thin-1.8.1/lib/thin/controllers/controller.rb:72:in `start'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/thin-1.8.1/lib/thin/runner.rb:203:in `run_command'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/thin-1.8.1/lib/thin/runner.rb:159:in `run!'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/thin-1.8.1/bin/thin:6:in `<top (required)>'
        from /home/ots/.rbenv/versions/2.6.10/bin/thin:25:in `load'
        from /home/ots/.rbenv/versions/2.6.10/bin/thin:25:in `<top (required)>'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:58:in `load'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:23:in `run'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.17/lib/bundler/cli.rb:483:in `exec'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.17/lib/bundler/cli.rb:31:in `dispatch'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.17/lib/bundler/cli.rb:25:in `start'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.17/exe/bundle:48:in `block in <top (required)>'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.17/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
        from /home/ots/.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.17/exe/bundle:36:in `<top (required)>'
        from /home/ots/.rbenv/versions/2.6.10/bin/bundle:25:in `load'
        from /home/ots/.rbenv/versions/2.6.10/bin/bundle:25:in `<main>'

ots@Onetime:~/onetimesecret$ bundle -v
Bundler version 2.3.17
ots@Onetime:~/onetimesecret$ ruby -v
ruby 2.6.10p210 (2022-04-12 revision 67958) [x86_64-linux]
ots@Onetime:~/onetimesecret$ rails -v
Rails 6.0.0
```
I appreciate if you can help me

**Comment by mislav** [comment]
Hi, sorry, but this is an issue tracker for rbenv issues only (regarding switching between Ruby versions).

Once a Ruby version is running, most errors that are thrown under it are due to app-specific code and its dependencies, and need to be debugged separately from rbenv. We can't help, unfortunately. Good luck!
