### ISSUE TITLE
`rails new` produces ` #<Thread:0x0000000102328d60 run>, #<NameError: uninitialized constant Gem::Source` result after making new app

### ISSUE THREAD

**Issue by jasonfb** [rbenv/rbenv#1429]
```
% rails new --skip-javascript MyGreatApp
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /Users/jason/Work/_LEARNING/ReactOnRails/MyGreatApp/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/new_framework_defaults_7_0.rb
      create  config/initializers/permissions_policy.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_7_0.rb
         run  bundle install
[61750, #<Thread:0x00000001050b8d48 run>, #<NameError: uninitialized constant Gem::Source

      (defined?(@source) && @source) || Gem::Source::Installed.new
                                           ^^^^^^^^
Did you mean?  Gem::SourceList>, ["/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/rubygems_ext.rb:18:in `source'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/rubygems_ext.rb:50:in `extension_dir'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/basic_specification.rb:339:in `have_file?'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/basic_specification.rb:86:in `contains_requirable_file?'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1038:in `block (2 levels) in find_in_unresolved_tree'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2555:in `block (2 levels) in traverse'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `each'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `block in traverse'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `each'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `traverse'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1034:in `block in find_in_unresolved_tree'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `each'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `find_in_unresolved_tree'", "<internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:114:in `require'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/rubygems_ext.rb:18:in `source'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/rubygems_ext.rb:50:in `extension_dir'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/basic_specification.rb:339:in `have_file?'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/basic_specification.rb:86:in `contains_requirable_file?'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1038:in `block (2 levels) in find_in_unresolved_tree'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2555:in `block (2 levels) in traverse'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `each'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `block in traverse'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `each'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `traverse'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1034:in `block in find_in_unresolved_tree'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `each'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `find_in_unresolved_tree'", "<internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:114:in `require'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:1:in `<top (required)>'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `require_relative'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `<top (required)>'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `require_relative'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `<top (required)>'", "<internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "<internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli/install.rb:50:in `run'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:255:in `block in install'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/settings.rb:131:in `temporary'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:254:in `install'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <main>'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<main>'"]]
[61750, #<Thread:0x00000001050b8d48 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["<internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require'", "<internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:1:in `<top (required)>'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `require_relative'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `<top (required)>'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `require_relative'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `<top (required)>'", "<internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "<internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli/install.rb:50:in `run'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:255:in `block in install'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/settings.rb:131:in `temporary'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:254:in `install'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <main>'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'", "/Users/jason/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<main>'"]]
/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/rubygems_ext.rb:18:in `source': uninitialized constant Gem::Source (NameError)

      (defined?(@source) && @source) || Gem::Source::Installed.new
                                           ^^^^^^^^
Did you mean?  Gem::SourceList
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/rubygems_ext.rb:50:in `extension_dir'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/basic_specification.rb:339:in `have_file?'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/basic_specification.rb:86:in `contains_requirable_file?'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1038:in `block (2 levels) in find_in_unresolved_tree'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2555:in `block (2 levels) in traverse'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `each'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `block in traverse'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `each'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `traverse'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1034:in `block in find_in_unresolved_tree'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `each'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `find_in_unresolved_tree'
	from <internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:114:in `require'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/rubygems_ext.rb:18:in `source'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/rubygems_ext.rb:50:in `extension_dir'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/basic_specification.rb:339:in `have_file?'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/basic_specification.rb:86:in `contains_requirable_file?'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1038:in `block (2 levels) in find_in_unresolved_tree'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2555:in `block (2 levels) in traverse'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `each'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `block in traverse'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `each'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `traverse'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1034:in `block in find_in_unresolved_tree'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `each'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `find_in_unresolved_tree'
	from <internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:114:in `require'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:26:in `log_error'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:109:in `rescue in with_friendly_errors'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:101:in `with_friendly_errors'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<main>'
<internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
	from <internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli/install.rb:50:in `run'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:255:in `block in install'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/settings.rb:131:in `temporary'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:254:in `install'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <main>'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<main>'
<internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
	from <internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:1:in `<top (required)>'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `require_relative'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `<top (required)>'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `require_relative'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `<top (required)>'
	from <internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli/install.rb:50:in `run'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:255:in `block in install'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/settings.rb:131:in `temporary'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:254:in `install'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <main>'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<main>'
/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/rubygems_ext.rb:18:in `source': uninitialized constant Gem::Source (NameError)

      (defined?(@source) && @source) || Gem::Source::Installed.new
                                           ^^^^^^^^
Did you mean?  Gem::SourceList
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/rubygems_ext.rb:50:in `extension_dir'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/basic_specification.rb:339:in `have_file?'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/basic_specification.rb:86:in `contains_requirable_file?'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1038:in `block (2 levels) in find_in_unresolved_tree'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2555:in `block (2 levels) in traverse'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `each'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `block in traverse'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `each'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `traverse'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1034:in `block in find_in_unresolved_tree'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `each'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `find_in_unresolved_tree'
	from <internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:114:in `require'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/rubygems_ext.rb:18:in `source'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/rubygems_ext.rb:50:in `extension_dir'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/basic_specification.rb:339:in `have_file?'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/basic_specification.rb:86:in `contains_requirable_file?'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1038:in `block (2 levels) in find_in_unresolved_tree'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2555:in `block (2 levels) in traverse'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `each'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `block in traverse'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `each'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `traverse'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1034:in `block in find_in_unresolved_tree'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `each'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `find_in_unresolved_tree'
	from <internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:114:in `require'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:1:in `<top (required)>'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `require_relative'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `<top (required)>'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `require_relative'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `<top (required)>'
	from <internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli/install.rb:50:in `run'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:255:in `block in install'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/settings.rb:131:in `temporary'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:254:in `install'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <main>'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/jason/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<main>'
         run  bundle binstubs bundler
Resolving dependencies...
jason@MBA22 /Users/jason/Work/_LEARNING/ReactOnRails 
% rbenv versions
  system
* 3.1.2 (set by /Users/jason/.rbenv/version)
jason@MBA22 /Users/jason/Work/_LEARNING/ReactOnRails 
% rails -v
Rails 7.0.4
jason@MBA22 /Users/jason/Work/_LEARNING/ReactOnRails 
% 
```

I don't know why this is happening or where this is coming from. 

It does the same thing if I try Rails 7.0.3.1

 `rails _7.0.3.1_ new --skip-javascript MyGreatApp2` 

the Rails app created, oddly, appears to be fine so I think this must be happening after the rails new has successfully completed. 

```
[63383, #<Thread:0x0000000102328d60 run>, #<NameError: uninitialized constant Gem::Source

      (defined?(@source) && @source) || Gem::Source::Installed.new
                                           ^^^^^^^^
```

**Comment by mislav** [comment]
Hi, this is a problem in either Rubygems or Rails, but not with rbenv, as most problems happening at Ruby runtime aren't the responsibility of rbenv anymore. You can try this:

```
ruby -r rubygems -e 'p Gem::Source'
```

It should be successful, but if it's not, then you can try upgrading Rubygems to the latest version (`gem update --system`). If the problem persists, please search the web for others encountering this issue.

**Comment by jasonfb** [comment]
ok thanks @mislav I have recently switched to rbenv so of course, I blame everything on rbenv but I realize that's not the culprit (!)

`gem update --system` fixed this thank you
