### ISSUE TITLE
When run `ruby --debug`, get lots of "Exception 'LoadError' at <shim>/kernel_require.rb:[83|160] - cannot load such file - <gem from Gemfile.lock file>" messages

### ISSUE THREAD

**Issue by philCryoport** [rbenv/rbenv#1431]
### Environment(s)
- `Linux ip-172-30-2-154 5.4.0-1085-aws #92~18.04.1-Ubuntu SMP Wed Aug 31 17:21:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Also seen on MacOS Monterey

### Steps to reproduce
1. Take existing rbenv installation that's up-to-date
2. `rbenv install 2.7.6`
3. `rbenv rehash`
4. `gem system --update`
5. `gem install bundler:<current stable version #>`
6. Configure Gemfile with lots of gems that are current (see Gemfile below)
8. Write ruby script to take advantage of some of those gems
9. `bundle install`
10. `bundle update`
11. `ruby --debug <ruby script file>`

```
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems.rb:1427 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems.rb:1435 - cannot load such file -- rubygems/defaults/ruby
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- amazing_print
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- mysql2
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- mail
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- postmark
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146 - cannot load such file -- tzinfo
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146 - cannot load such file -- concurrent/concurrent_ruby_ext
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- concurrent/concurrent_ruby_ext
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146 - cannot load such file -- concurrent/2.7/concurrent_ruby_ext
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- concurrent/2.7/concurrent_ruby_ext
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146 - cannot load such file -- caxlsx
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8/lib/nokogiri/extension.rb:7 - cannot load such file -- /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8/lib/nokogiri/2.7/nokogiri
Exception `SyntaxError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/forwardable/impl.rb:5 - /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/forwardable/impl.rb:5: syntax error, unexpected end-of-input
Exception `SyntaxError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/forwardable/impl.rb:5 - /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/forwardable/impl.rb:5: syntax error, unexpected end-of-input
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146 - cannot load such file -- aws-sdk-s3
Using Ext extension for JSON.
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- http/2
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- http/2
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- http/2
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- http/2
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- ox
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- ox
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- ox
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- oga
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- oga
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- oga
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- libxml
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- libxml
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- libxml
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- oj
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- oj
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- oj
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- oj
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- aws-crt
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- aws-crt
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- aws-crt
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- aws-crt
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- net/sftp
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- 2.7/bcrypt_pbkdf_ext
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- 2.7/bcrypt_pbkdf_ext
Exception `Gem::MissingSpecError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/dependency.rb:311 - Gem::MissingSpecError
Exception `Gem::MissingSpecError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - Gem::MissingSpecError
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- tzinfo/data
```

How do I get rid of these "LoadErrors" for these gems?

The "Gem::MissingSpecError"'s are probably goofs of the gems themselves.

Gemfile:
```
➜ cat Gemfile
# frozen_string_literal: true

source 'https://rubygems.org'
gem 'amazing_print'
gem 'american_date'
gem 'aws-sdk-s3'
gem 'bcrypt_pbkdf'
gem 'caxlsx'
gem 'ed25519'
gem 'faraday'
gem 'gemsurance'
gem 'mail'
gem 'mysql2'
gem 'net-sftp'
gem 'postmark', '>=1.21.3'
gem 'psych'
gem 'rubocop', require: false
gem 'syslogger'
gem 'tzinfo'
gem 'tzinfo-data'

group :development do
  gem 'debase'
  gem 'ruby-debug-ide'
end%
```

**Comment by philCryoport** [comment]
### Environment(s)
- Linux ip-172-30-2-154 5.4.0-1085-aws #92~18.04.1-Ubuntu SMP Wed Aug 31 17:21:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Also seen on MacOS Monterey

### Steps to reproduce
1. Take existing rbenv installation that's up-to-date
2. `rbenv install 2.7.6`
3. `rbenv rehash`
4. `gem system --update`
5. `gem install bundler:<current stable version #>`
6. Configure Gemfile with lots of gems that are current
7. Write ruby script to take advantage of some of those gems
8. `bundle install`
9. `bundle update`
10. `ruby --debug <ruby script file>`

```
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems.rb:1427 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems.rb:1435 - cannot load such file -- rubygems/defaults/ruby
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- amazing_print
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- mysql2
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- mail
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- postmark
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146 - cannot load such file -- tzinfo
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146 - cannot load such file -- concurrent/concurrent_ruby_ext
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- concurrent/concurrent_ruby_ext
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146 - cannot load such file -- concurrent/2.7/concurrent_ruby_ext
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- concurrent/2.7/concurrent_ruby_ext
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146 - cannot load such file -- caxlsx
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8/lib/nokogiri/extension.rb:7 - cannot load such file -- /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8/lib/nokogiri/2.7/nokogiri
Exception `SyntaxError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/forwardable/impl.rb:5 - /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/forwardable/impl.rb:5: syntax error, unexpected end-of-input
Exception `SyntaxError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/forwardable/impl.rb:5 - /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/forwardable/impl.rb:5: syntax error, unexpected end-of-input
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146 - cannot load such file -- aws-sdk-s3
Using Ext extension for JSON.
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- http/2
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- http/2
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- http/2
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- http/2
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- ox
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- ox
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- ox
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- oga
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- oga
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- oga
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- libxml
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- libxml
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- libxml
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- oj
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- oj
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- oj
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- oj
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- aws-crt
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- aws-crt
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- aws-crt
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- aws-crt
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- net/sftp
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- 2.7/bcrypt_pbkdf_ext
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - cannot load such file -- 2.7/bcrypt_pbkdf_ext
Exception `Gem::MissingSpecError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/dependency.rb:311 - Gem::MissingSpecError
Exception `Gem::MissingSpecError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160 - Gem::MissingSpecError
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83 - cannot load such file -- tzinfo/data
```

How do I get rid of these "LoadErrors" for these gems?

The "Gem::MissingSpecError"'s are probably goofs of the gems themselves.

**Comment by mislav** [comment]
Hi, this is a general Bundler question, not rbenv one. If you want to execute a Ruby script in the context of your bundle, you must use `bundle exec <command>`. In your case:

```
bundle exec ruby --debug <file>
```

**Comment by philCryoport** [comment]
> Hi, this is a general Bundler question, not rbenv one. If you want to execute a Ruby script in the context of your bundle, you must use `bundle exec <command>`. In your case:
> 
> ```
> bundle exec ruby --debug <file>
> ```

Hi @mislav  please re-open.  Some of the error messages disappeared now that I'm using `bundle exec ruby --debug <file>` -- but many still remain:
```
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems.rb:1427 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems.rb:1435 - cannot load such file -- rubygems/defaults/ruby
Exception `NameError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/rubygems_integration.rb:458 - method `gem' not defined in #<Class:Kernel>
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/utility/native_extension_loader.rb:62 - cannot load such file -- concurrent/concurrent_ruby_ext
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/utility/native_extension_loader.rb:62 - cannot load such file -- concurrent/2.7/concurrent_ruby_ext
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8/lib/nokogiri/extension.rb:7 - cannot load such file -- /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8/lib/nokogiri/2.7/nokogiri
Exception `SyntaxError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/forwardable/impl.rb:5 - /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/forwardable/impl.rb:5: syntax error, unexpected end-of-input
Exception `SyntaxError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/forwardable/impl.rb:5 - /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/2.7.0/forwardable/impl.rb:5: syntax error, unexpected end-of-input
Using Ext extension for JSON.
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.152.0/lib/seahorse/client/h2/connection.rb:4 - cannot load such file -- http/2
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.152.0/lib/seahorse/client/h2/handler.rb:4 - cannot load such file -- http/2
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.152.0/lib/aws-sdk-core/xml/parser/engines/ox.rb:3 - cannot load such file -- ox
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.152.0/lib/aws-sdk-core/xml/parser/engines/oga.rb:3 - cannot load such file -- oga
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.152.0/lib/aws-sdk-core/xml/parser/engines/libxml.rb:3 - cannot load such file -- libxml
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.152.0/lib/aws-sdk-core/json/oj_engine.rb:28 - cannot load such file -- oj
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.152.0/lib/aws-sdk-core/json.rb:39 - cannot load such file -- oj
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.152.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:14 - cannot load such file -- aws-crt
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/aws-sigv4-1.5.1/lib/aws-sigv4/signer.rb:79 - cannot load such file -- aws-crt
Exception `Ed25519::VerifyError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/ed25519-1.3.0/lib/ed25519/verify_key.rb:29 - signature verification failed!
Exception `LoadError' at /home/ubuntu/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bcrypt_pbkdf-1.1.0/lib/bcrypt_pbkdf.rb:3 - cannot load such file -- 2.7/bcrypt_pbkdf_ext
```

Help?

**Comment by mislav** [comment]
Sorry, but rbenv doesn't manage every aspect of your Ruby runtime. It looks like you wanted to activate Ruby 2.7.6 and rbenv did just that for you. I have no idea why these load errors happen on your end, but since you are the only one of the two of us who have access to your machine, you are in a unique position to be able to debug this.

My Ruby 2.7.5 version does not contain the file reported among the first one of your LoadErrors listed:
```
%  RBENV_VERSION=2.7.5 ruby -r rubygems -e 'require "rubygems/defaults/operating_system"'
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from /Users/mislav/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Users/mislav/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- rubygems/defaults/operating_system (LoadError)
```

The Rubygems project, where the error seems to stem from, also does not seem to include a file with that filename: https://github.com/rubygems/rubygems/tree/master/lib/rubygems

In fact, this conversation in their issue tracker seems to hint that this file comes "from the operating system": https://github.com/rubygems/rubygems/pull/4824

What exactly requires this file when you start your ruby script, I do not know! But maybe you can figure it out? You can search for filenames in your local installation like this:
```sh
find "$(rbenv prefix 2.7.6)" -name 'operating_system.rb'
```

Look up whether your rbenv has any plugins installed that might be injecting their own behavior:
```sh
ls "$(rbenv root)"/plugins
```

Check your environment variables for ruby-related settings:
```sh
env | grep -i ruby
```

And finally, see if you can replicate the problem in a fresh project, i.e. outside of your existing project.

> `gem system --update`

This should be `gem update --system`.

**Comment by hsbt** [comment]
@philCryoport It's missing with `bundle exec` command for `ruby --debug`. But I'm not sure the root cause of this issue.
