### ISSUE TITLE
Ruby 2.2.10 install fails due to OpenSSL issue

### ISSUE THREAD

**Issue by tsvallender** [rbenv/rbenv#1557]
I’m attempting to install this ancient version of Ruby and hitting this issue.

Initial output of `rbenv install`:
```
==> Downloading openssl-1.0.2u.tar.gz...
-> curl -q -fL -o openssl-1.0.2u.tar.gz https://dqw8nmjcqpjn7.cloudfront.net/ecd0c6ffb493dd06707d38b14bb4d8c2288bb7033735606569d8f90f89669
d16
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5229k  100 5229k    0     0  30.2M      0 --:--:-- --:--:-- --:--:-- 30.4M
==> Installing openssl-1.0.2u...
-> ./config "--prefix=$HOME/.rbenv/versions/2.2.10/openssl" "--openssldir=$HOME/.rbenv/versions/2.2.10/openssl/ssl" zlib-dynamic no-ssl3 s
hared no-ssl2 no-krb5
-> make -j 32
-> make install_sw
==> Installed openssl-1.0.2u to /home/tsv/.rbenv/versions/2.2.10
==> Downloading ruby-2.2.10.tar.bz2...
-> curl -q -fL -o ruby-2.2.10.tar.bz2 https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.10.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.7M  100 12.7M    0     0  26.9M      0 --:--:-- --:--:-- --:--:-- 26.9M
==> Installing ruby-2.2.10...

WARNING: ruby-2.2.10 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.

-> ./configure "--prefix=$HOME/.rbenv/versions/2.2.10" "--with-openssl-dir=$HOME/.rbenv/versions/2.2.10/openssl"
-> make -j 32
-> make install

BUILD FAILED (openSUSE Tumbleweed 20240314 on x86_64 using ruby-build 20240221)

You can inspect the build directory at /tmp/ruby-build.20240318154710.5688.egFgj5
See the full build log at /tmp/ruby-build.20240318154710.5688.log
```

The referenced log file ends with:
```
/tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require': libssl.so.1.0.0: cannot open shared object file: No such file or directory - /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/.ext/x86_64-linux/openssl.so (LoadError)
        from /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/.ext/common/openssl.rb:17:in `<top (required)>'
        from /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/lib/rubygems/security.rb:11:in `<top (required)>'
        from /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/lib/rubygems/package.rb:43:in `<top (required)>'
        from /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/lib/rubygems/dependency_installer.rb:3:in `<top (required)>'
        from /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /tmp/ruby-build.20240318154710.5688.egFgj5/ruby-2.2.10/lib/rubygems.rb:556:in `install'
        from ./tool/rbinstall.rb:722:in `block (2 levels) in <main>'
        from ./tool/rbinstall.rb:721:in `each'
        from ./tool/rbinstall.rb:721:in `block in <main>'
        from ./tool/rbinstall.rb:757:in `call'
        from ./tool/rbinstall.rb:757:in `block in <main>'
        from ./tool/rbinstall.rb:754:in `each'
        from ./tool/rbinstall.rb:754:in `<main>'
make: *** [uncommon.mk:246: do-install-all] Error 1
external command failed with status 2
/tmp/ruby-1build.20240318154710.5688.egFgj5/ruby2.2.10/.ext/x86_64-linux/openssl.so
```

The file `/tmp/rubybuild.20240318154710.5688.egFgj5/ruby2.2.10/.ext/x86_64linux/openssl.so` _does_ exist, however. Is that the file it’s claiming doesn’t exist?

**Comment by tsvallender** [comment]
After a little more investigation, this is likely relevant:
```
ldd /tmp/ruby-build.20240319084848.25667.bjUEBD/ruby-2.2.10/.ext/x86_64-linux/openssl.so 
        linux-vdso.so.1 (0x00007ffcd4b29000)
        libssl.so.1.0.0 => not found
        libcrypto.so.1.0.0 => not found
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fb10c8a8000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fb10c7bf000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb10c400000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb10c94e000)
```
