### ISSUE TITLE
rbenv gem install nokogiri fails

### ISSUE THREAD

**Issue by mhenrixon** [rbenv/rbenv#296]
Installing nokogiri with sudo gem install works like a charm but installing it with bundle install fails. It also fails to install the gem without sudo. I've tried installing ruby 1.9.3-p327 I don't know how many times now with the same results using ruby build. Feels like I am missing something really simple.

``` sh
mhenrixon@mhenrixon-VirtualBox:~/github/taskk$ sudo gem install nokogiri -v '1.5.5'
[sudo] password for mhenrixon: 
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.5.5
1 gem installed
```

``` sh
Installing nokogiri (1.5.5) with native extensions 
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /home/mhenrixon/.rbenv/versions/1.9.3-p327/bin/ruby extconf.rb 
checking for libxml/parser.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/home/mhenrixon/.rbenv/versions/1.9.3-p327/bin/ruby
    --with-zlib-dir
    --without-zlib-dir
    --with-zlib-include
    --without-zlib-include=${zlib-dir}/include
    --with-zlib-lib
    --without-zlib-lib=${zlib-dir}/lib
    --with-iconv-dir
    --without-iconv-dir
    --with-iconv-include
    --without-iconv-include=${iconv-dir}/include
    --with-iconv-lib
    --without-iconv-lib=${iconv-dir}/lib
    --with-xml2-dir
    --without-xml2-dir
    --with-xml2-include
    --without-xml2-include=${xml2-dir}/include
    --with-xml2-lib
    --without-xml2-lib=${xml2-dir}/lib
    --with-xslt-dir
    --without-xslt-dir
    --with-xslt-include
    --without-xslt-include=${xslt-dir}/include
    --with-xslt-lib
    --without-xslt-lib=${xslt-dir}/lib
    --with-libxslt-config
    --without-libxslt-config
    --with-pkg-config
    --without-pkg-config
    --with-libxml-2.0-config
    --without-libxml-2.0-config
    --with-libiconv-config
    --without-libiconv-config
/home/mhenrixon/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /home/mhenrixon/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:506:in `try_cpp'
    from /home/mhenrixon/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:970:in `block in find_header'
    from /home/mhenrixon/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
    from /home/mhenrixon/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
    from /home/mhenrixon/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:254:in `open'
    from /home/mhenrixon/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
    from /home/mhenrixon/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:254:in `open'
    from /home/mhenrixon/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
    from /home/mhenrixon/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
    from /home/mhenrixon/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:969:in `find_header'
    from extconf.rb:114:in `<main>'


Gem files will remain installed in /home/mhenrixon/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/nokogiri-1.5.5 for inspection.
Results logged to /home/mhenrixon/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/nokogiri-1.5.5/ext/nokogiri/gem_make.out
An error occurred while installing nokogiri (1.5.5), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.5.5'` succeeds before bundling.
```

**Comment by alirezarahmani** [comment]
the key is 

bundle config build.nokogiri "--use-system-libraries --with-xml2-include=/usr/local/opt/libxml2/include/libxml2"
