### ISSUE TITLE
gem in rbenv cause LoadError

### ISSUE THREAD

**Issue by pixyonly** [rbenv/rbenv#905]
Hi,
I doubt whether the question should be here or in gem project. I think guys here are more kindly : )

Environment:
system: mac 10.11.5 EI Captain
shell: zsh + oh-my-zsh
rbenv settings:

```
$ rbenv version                                                                                                     
1.9.3-p551 (set by /Users/pixyonly/.ruby-version)
```

Description:
I install some gems with system ruby, it works fine(after i uninstalled rbenv)
but using gem in rbenv got the fault:

`$gem install bundler`

```
/Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- socket (LoadError)
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/net/protocol.rb:21:in `<top (required)>'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/net/http.rb:22:in `<top (required)>'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/remote_fetcher.rb:58:in `initialize'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/remote_fetcher.rb:43:in `new'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/remote_fetcher.rb:43:in `fetcher'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/spec_fetcher.rb:66:in `initialize'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/spec_fetcher.rb:43:in `new'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/spec_fetcher.rb:43:in `fetcher'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/dependency_installer.rb:110:in `find_gems_with_sources'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/dependency_installer.rb:228:in `find_spec_by_name_and_version'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/dependency_installer.rb:259:in `install'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/commands/install_command.rb:121:in `block in execute'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/commands/install_command.rb:115:in `each'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/commands/install_command.rb:115:in `execute'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/command.rb:278:in `invoke'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/command_manager.rb:147:in `process_args'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/command_manager.rb:117:in `run'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/gem_runner.rb:65:in `run'
    from /Users/pixyonly/.rbenv/versions/1.9.3-p551/bin/gem:21:in `<main>'
```

I doubt the key is the strange path:

>  /Users/pixyonly/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems

I tried to reinstall rbenv and delete the directory ~/.rbenv, but still have the problem.

**Comment by syndory** [comment]
I think i find it. Pardon me for disturbing。
https://github.com/rbenv/ruby-build/issues/815#issuecomment-184309845

**Comment by syndory** [comment]
still the same problem. [rbenv/ruby-build](https://github.com/rbenv/ruby-build/issues/815#issuecomment-184309845) is not suit for me.

I tried rbenv-doctor: 
```
$ curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | sh                       
-n Checking for `rbenv' in PATH:
/usr/local/bin/rbenv
-n Checking for rbenv shims in PATH:
OK
-n Checking `rbenv install' support:
/usr/local/bin/rbenv-install (ruby-build 20160426)
-n Counting installed Ruby versions:
2 versions
-n Checking RubyGems settings:
OK
-n Auditing installed plugins:
OK
```
Ehm....

**Comment by mislav** [comment]
Sorry for the late reply. I think you have everything set up regarding rbenv correctly. I don't think the problem is in rbenv nor ruby-build. Instead, the problem is somewhere in the Ruby version that you're using. I hope you were able to solve it.
