### ISSUE TITLE
rbenv/foreman Permission denied @ rb_sysopen - /etc/init/app.conf (Errno::EACCES)

### ISSUE THREAD

**Issue by dcalixto** [rbenv/rbenv#913]
**Someone knows how to give rbenv permission to rbenv/foreman export?
thank's**

```
[foreman export] writing: app.conf
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foreman-0.82.0/lib/foreman/export/base.rb:162:in `initialize': Permission denied @ rb_sysopen - /etc/init/app.conf (Errno::EACCES)
    from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foreman-0.82.0/lib/foreman/export/base.rb:162:in `open'
    from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foreman-0.82.0/lib/foreman/export/base.rb:162:in `write_file'
    from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foreman-0.82.0/lib/foreman/export/base.rb:139:in `write_template'
    from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foreman-0.82.0/lib/foreman/export/upstart.rb:12:in `export'
    from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foreman-0.82.0/lib/foreman/cli.rb:61:in `export'
    from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foreman-0.82.0/bin/foreman:7:in `<top (required)>'
    from /home/ubuntu/.rbenv/versions/2.2.2/bin/foreman:23:in `load'
    from /home/ubuntu/.rbenv/versions/2.2.2/bin/foreman:23:in `<main>'

```

**Comment by mislav** [comment]
Hello,

For Foreman to be able to write to `/etc/init/app.conf`, the while either has to be writeable by the user who is running Foreman, or you should use `sudo foreman`. In any case, this has nothing to do with rbenv.

**Comment by dcalixto** [comment]
right, thank you @mislav

**Comment by vanmart** [comment]
what suposed to do... on file or directory... no local or remote server u.u damn im tired... Thanks for your time---
