### ISSUE TITLE
Unable to run gem after upgrade ruby to 2.3.1 using rbenv

### ISSUE THREAD

**Issue by zwang** [rbenv/rbenv#947]
```
➜  ~ rbenv which gem
/usr/local/var/rbenv/versions/2.3.1/bin/gem
➜  ~ which gem
/usr/local/var/rbenv/shims/gem
➜  ~ /usr/local/var/rbenv/versions/2.3.1/bin/gem update
Ignoring bigdecimal-1.2.7 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.2.7
Ignoring io-console-0.4.6 because its extensions are not built.  Try: gem pristine io-console --version 0.4.6
Ignoring json-2.0.2 because its extensions are not built.  Try: gem pristine json --version 2.0.2
Ignoring psych-2.1.1 because its extensions are not built.  Try: gem pristine psych --version 2.1.1
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /usr/local/opt/gems/gems/io-console-0.4.6/lib/io/console.bundle (fatal)
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/user_interaction.rb:9:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/command.rb:10:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/command_manager.rb:8:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/gem_runner.rb:9:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/bin/gem:9:in `<main>'
➜  ~ rbenv versions
  system
* 2.3.1 (set by /usr/local/var/rbenv/version)
➜  ~ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
```

Have to run `sudo gem update` for things to work.

**Comment by mislav** [comment]
Thanks for reporting, but I can't see how this could be an error with rbenv when you didn't even use rbenv to invoke the `gem update` command (you went directly to the binary). More likely this is a bug with RubyGems, or something involving your environment. For instance, what is the `/usr/local/opt/gems/gems/io-console-0.4.6` directory, and how does it play a role here? What happens if you nuke the `/usr/local/opt/gems` directory?
