### ISSUE TITLE
Getting LoadError with locally developed gem

### ISSUE THREAD

**Issue by alvincrespo** [rbenv/rbenv#957]
I'm developing a gem and when I try to install it on Mac OSX Sierra, I get this error:

```
➜  latest mygem test_file.txt
/Users/alvincrespo/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'mygem' (>= 0.a) among 0 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/alvincrespo/.gem/ruby/2.3.0:/Users/alvincrespo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /Users/alvincrespo/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /Users/alvincrespo/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /Users/alvincrespo/.rbenv/versions/2.3.0/bin/mygem:22:in `<main>'
```

To be clear this only happens on Mac OSX Sierra, on OSX El Capitan everything works perfectly.  Here is my `gem env`output:

```
➜  latest gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-darwin16]
  - INSTALLATION DIRECTORY: /Users/alvincrespo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/alvincrespo/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/alvincrespo/.rbenv/versions/2.3.0/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/alvincrespo/.rbenv/versions/2.3.0/bin
  - SPEC CACHE DIRECTORY: /Users/alvincrespo/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/alvincrespo/.rbenv/versions/2.3.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-16
  - GEM PATHS:
     - /Users/alvincrespo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0
     - /Users/alvincrespo/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/alvincrespo/.rbenv/versions/2.3.0/bin
     - /usr/local/Cellar/rbenv/1.1.0/libexec
     - /Users/alvincrespo/.rbenv/shims
     - /Users/alvincrespo/.nvm/versions/node/v7.2.0/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/go/bin
```

I'm using homebrew with rbenv and ruby-build. 

Any help with this would be greatly appreciated. Thanks in advance!

**Comment by alvincrespo** [comment]
For additional information information, the gem was created with bundler, and inside of `mygem/bin/mygem`it has this:

```
#!/usr/bin/env ruby
require "mygem"

# Does some stuff after this line
```

**Comment by mislav** [comment]
Sorry, this sounds like a usage question and not a bug with rbenv. We can't help you with developing your own gems. Good luck!

**Comment by tcd** [comment]
@mislav Where would be the correct place to look for a solution to this problem?
