### ISSUE TITLE
Readline issue while typing arrow keys.

### ISSUE THREAD

**Issue by kumarn33** [rbenv/rbenv#964]
``` shell
λ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin14]
[tmp]
λ rbenv -v
rbenv 1.1.0
[tmp]
λ irb
irb(main):001:0> ^[[A
irb(main):001:0> require 'readline'
LoadError: dlopen(/Users/deepak/.rbenv/versions/2.4.0/lib/ruby/2.4.0/x86_64-darwin14/readline.bundle, 9): Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /Users/deepak/.rbenv/versions/2.4.0/lib/ruby/2.4.0/x86_64-darwin14/readline.bundle
  Reason: image not found - /Users/deepak/.rbenv/versions/2.4.0/lib/ruby/2.4.0/x86_64-darwin14/readline.bundle
       	from /Users/deepak/.rbenv/versions/2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /Users/deepak/.rbenv/versions/2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from (irb):1
       	from /Users/deepak/.rbenv/versions/2.4.0/bin/irb:11:in `<main>'
irb(main):002:0>
```

**Comment by mislav** [comment]
You must have at some point had `/usr/local/opt/readline/lib/libreadline.6.dylib` installed via Homebrew, but you have since then upgraded the Homebrew package and now only have `/usr/local/opt/readline/lib/libreadline.7.dylib` (I'm guessing). Ruby is trying to dynamically load libreadline.6 which is not there anymore. You have to other:

1. Revert the Homebrew version somehow; or
2. Reinstall Ruby to have it linked to the newer libreadline version.

**Comment by kumarn33** [comment]
@mislav Thank, that was the issue, I created a symlink libreadline.6.dylib to libreadline.7.dylib and verified this :-) and that worked.

**Comment by mislav** [comment]
Thanks for updating!
