### ISSUE TITLE
Running specific Rails version

### ISSUE THREAD

**Issue by ivanovaleksey** [rbenv/rbenv#989]
Hi guys,

some time ago I had an issue of running specific Rails version https://github.com/rails/rails/issues/27456.
That time I solved it by just updating rubygems.

But now I faced with the problem once again. There is also the same [comment](https://github.com/rails/rails/issues/27456#issuecomment-278629438) from @hallelujah.

I use Ruby 2.3.4 and running `rails _4.2.8_ -v` gives me `Rails 5.0.2`.
But I noticed that everything works fine with Ruby 2.3.3.
I tried to solve the problem myself but I didn't find anything 😞 

I tried to look at `$LOAD_PATH` at different times to see how it changed.

**USING RUBY 2.3.3**
In the end of `/Users/aleksey/.rbenv/versions/2.3.3/bin/rails` I have 
```
/usr/local/Cellar/rbenv/1.1.0/rbenv.d/exec/gem-rehash
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin16
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/site_ruby
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/vendor_ruby/2.3.0
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin16
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/vendor_ruby
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/2.3.0
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/2.3.0/x86_64-darwin16
```

This file then loads `/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/bin/rails`. In the very beginning `$LOAD_PATH` is 
```
/usr/local/Cellar/rbenv/1.1.0/rbenv.d/exec/gem-rehash
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-test-0.6.3/lib
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/loofah-2.0.3/lib
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rails-html-sanitizer-1.0.3/lib
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/erubis-2.7.0/lib
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.8/lib
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin16
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/site_ruby
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/vendor_ruby/2.3.0
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin16
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/vendor_ruby
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/2.3.0
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/2.3.0/x86_64-darwin16
```

So at that moment it already includes railties-4.2.8 (I don't know where it happens)
However the strange thing is that I have some errors in console:
```
$ rails _4.2.8_ -v
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/cli.rb:5:in `<top (required)>'
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/bin/rails:17:in `<top (required)>'
/Users/aleksey/.rbenv/versions/2.3.3/bin/rails:23:in `load'
/Users/aleksey/.rbenv/versions/2.3.3/bin/rails:23:in `<main>'
Rails 4.2.8
```

**USING RUBY 2.3.4**

The `$LOAD_PATH` is always:
```
/usr/local/Cellar/rbenv/1.1.0/rbenv.d/exec/gem-rehash
/Users/aleksey/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Users/aleksey/.rbenv/versions/2.3.4/lib/ruby/site_ruby/2.3.0
/Users/aleksey/.rbenv/versions/2.3.4/lib/ruby/site_ruby/2.3.0/x86_64-darwin16
/Users/aleksey/.rbenv/versions/2.3.4/lib/ruby/site_ruby
/Users/aleksey/.rbenv/versions/2.3.4/lib/ruby/vendor_ruby/2.3.0
/Users/aleksey/.rbenv/versions/2.3.4/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin16
/Users/aleksey/.rbenv/versions/2.3.4/lib/ruby/vendor_ruby
/Users/aleksey/.rbenv/versions/2.3.4/lib/ruby/2.3.0
/Users/aleksey/.rbenv/versions/2.3.4/lib/ruby/2.3.0/x86_64-darwin16
```

The same thing happens with another gems, for instance, `thor` gem.

I use 
```
$ rbenv --version
rbenv 1.1.0

$ gem --version
2.6.11 (for both 2.3.3 and 2.3.4)
```

Could you please help me to understand what is wrong with my rbenv configuration?

Thank you.

**Comment by ivanovaleksey** [comment]
Stupid me...
I didn't notice that Rails bin stubs for 2.3.3 and 2.3.4 are different:

```
$ less /Users/aleksey/.rbenv/versions/2.3.4/bin/ruby
...
load Gem.bin_path('railties', 'rails', version)
```


```
$ less /Users/aleksey/.rbenv/versions/2.3.3/bin/ruby
...
load Gem.activate_bin_path('railties', 'rails', version)
```

This is exactly what @tenderlove fixed in https://github.com/rubygems/rubygems/pull/1527

The question now is how can I properly regenerate this `<ruby-prefix>/bun/rails`?
Does rubygems have any command for this?

If I do `gem uninstall rails` it doesn't remove `<ruby-prefix>/bun/rails`. So when I install rails once again I still have the same `<ruby-prefix>/bun/rails`.

If I remove `<ruby-prefix>/bun/rails` manually it isn't generated after installing rails gem.
So now I have 
```
$ rails -v
rbenv: rails: command not found

The `rails' command exists in these Ruby versions:
  2.2.2
  2.2.3
  2.3.1
  2.3.3
```

**Comment by ivanovaleksey** [comment]
Stupid me once again...
I forgot that `rails` executable comes form railties gem.
After reinstalling railties gem `<ruby-prefix>/bun/rails` was regenerated with `Gem.activate_bin_path`

The last question is about strange errors under Ruby 2.3.3
```
$ rails _4.2.8_ -v
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/cli.rb:5:in `<top (required)>'
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/bin/rails:17:in `<top (required)>'
/Users/aleksey/.rbenv/versions/2.3.3/bin/rails:23:in `load'
/Users/aleksey/.rbenv/versions/2.3.3/bin/rails:23:in `<main>'
Rails 4.2.8
```

What can cause this errors?

**Comment by mislav** [comment]
Sorry for late reply! This doesn't sound like a bug or strange behavior with rbenv, which merely switches between _Ruby_ versions (not gem versions). Everything that happens when executing a Ruby process is no longer affected by rbenv anymore.
